queuemining/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'queuemining'


urlpatterns = [
    path('', views.get_data, name='get_data'),
    path('view_table', views.view_table, name='view_table'),
    path('view_analysis', views.view_analysis, name='view_analysis')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

queueminingprojectOP/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('queuemining/',include('queuemining.urls') ),
]

queuemining/models.py
from django.db import models
from .validator import validate_file_extension


class DataFrame(models.Model):
    act_id = models.IntegerField(default=0)
    case_amount = models.DecimalField(max_digits=20, decimal_places=10)
    act_name = models.CharField(default="Activity", max_length=400)
    service_time = models.DecimalField(max_digits=20, decimal_places=10)
    waiting_time = models.DecimalField(max_digits=20, decimal_places=10)
    res_nr = models.DecimalField(max_digits=20, decimal_places=10)
    capacity = models.DecimalField(max_digits=20, decimal_places=10)


class TimeStep(models.Model):
    timeframe = models.IntegerField(default=1)
    unit = models.CharField(max_length=10)
    frame = models.ManyToManyField(DataFrame)

    def __str__(self):
        if self.unit == "H":
            output = str(self.timeframe) + " Hour(s)"
        elif self.unit == "D":
            output = str(self.timeframe) + " Day(s)"
        elif self.unit == "W":
            output = str(self.timeframe) + " Week(s)"
        elif self.unit == "M":
            output = str(self.timeframe) + " Month(s)"
        return output


class Data(models.Model):
    document = models.FileField(upload_to='documents/', validators=[validate_file_extension])
    uploaded_at = models.DateTimeField(auto_now_add=True)
    offdays = models.CharField(default="7", max_length=100)
    day_start = models.IntegerField(default=1)
    day_end = models.IntegerField(default=1)
    timestep = models.ManyToManyField(TimeStep)

queuemining/forms.py
from django import forms
from .models import Data, TimeStep


class DataForm(forms.ModelForm):
    class Meta:
        model = Data
        fields = ('document', 'timeframe', 'unit', 'offdays', 'day_start', 'day_end')
    UNIT_CHOICES = (
            ("N", "---"),
            ("H", "Hour"),
            ("D", "Day"),
            ("W", "Week"),
            ("M", "Month")
    )
    DAY_CHOICES = (
            ("0", "No Offdays"),
            ("1", "Monday"),
            ("2", "Tuesday"),
            ("3", "Wednesday"),
            ("4", "Thursday"),
            ("5", "Friday"),
            ("6", "Saturday"),
            ("7", "Sunday"),
    )
    timeframe = forms.IntegerField(initial=1)
    unit = forms.ChoiceField(label='Unit', choices=UNIT_CHOICES)
    offdays = forms.MultipleChoiceField(choices=DAY_CHOICES, widget=forms.SelectMultiple)
    day_start = forms.IntegerField(initial=9)
    day_end = forms.IntegerField(initial=17)


class TimeForm(forms.ModelForm):
    class Meta:
        model = TimeStep
        fields = ('timeframe', 'unit', )
    UNIT_CHOICES = (
        ("N", "---"),
        ("H", "Hour"),
        ("D", "Day"),
        ("W", "Week"),
        ("M", "Month")
    )
    timeframe = forms.IntegerField(initial=1, required=False)
    unit = forms.ChoiceField(label='unit', choices=UNIT_CHOICES, required=False)


class CurrentForm(forms.Form):
    timestep = forms.ModelChoiceField(
        queryset=None,
        required=False, empty_label="---", label='Current')

    def __init__(self, request, *args, **kwargs):
        super(CurrentForm, self).__init__(*args, **kwargs)
        if not request is None:
            data_id = request.session['data_id']
            query = Data.objects.get(id=data_id).timestep.all()
            self.fields['timestep'].queryset = query
            self.fields['timestep'].widget.choices = self.fields['timestep'].choices
            self.fields['timestep'].id = 'current'

queuemining/views.py
from django.shortcuts import render
import random
from django.http import HttpResponse
from . import forms
from django.template import loader
from . import utils
import matplotlib.pyplot as plt
import csv
import os
from django.conf import settings


def get_data(request):
    """Get data is the view used to manage the upload of the event log,
     as well as all of the data needed for our calculations."""
    random.seed(10)
    context = {}
    if request.method == 'POST':
        data_form = forms.DataForm(request.POST, request.FILES)
        if utils.data_valid(data_form) and utils.hours_valid(data_form):
            utils.submit_data(data_form, request)
            text = "Thank you for your upload!"
        else:
            data_form = forms.DataForm()
            text = "Your input was not usable by the system. Please redo!"
        context['text'] = text
    else:
        data_form = forms.DataForm()
        utils.wipe_data(request)
        context['text'] = "Please enter the respective data into the sidebar!"
    context['data_form'] = data_form
    template = loader.get_template('main.html')
    return HttpResponse(template.render(context, request))


def view_table(request):
    """View table is the view used to manage the creation and visualization of tables for each timestep."""
    context = {}
    if request.method == 'POST':
        time_form = forms.TimeForm(request.POST)
        current_form = forms.CurrentForm(request, request.POST)
        if 'time_submit' in time_form.data:
            if utils.data_valid(time_form):
                if not utils.time_used(time_form, request):
                    utils.submit_time(time_form, request)
                    time_text = "Thank you for your upload!"
                else:
                    time_text = "This timeframe was already used!"
            else:
                time_form = forms.TimeForm()
                time_text = "Your timeframe wasn't submittable"
            context['time_text'] = time_text
        elif 'time_delete_all' in time_form.data:
            time_form = forms.TimeForm()
            if utils.delete_time_all(request):
                delete_text = "All timesteps have been deleted!"
            else:
                delete_text = "There are no timesteps to delete!"
            context['delete_text'] = delete_text
        elif 'time_delete' in time_form.data:
            time_form = forms.TimeForm()
            if utils.delete_time(request):
                delete_text = "The current timestep has been deleted!"
            else:
                delete_text = "There are no timesteps to delete!"
            context['delete_text'] = delete_text
        if current_form.is_valid() and not current_form.cleaned_data['timestep'] is None:
            utils.submit_current(current_form, request)
    else:
        time_form = forms.TimeForm()
        current_form = forms.CurrentForm(request)
    if not request.session['current_time'] is None:
        df = utils.show_dataframe(request.session['cur_timestep'])
        table_data = df.to_html()
    else:
        table_data = "<p>Please submit a timestep</p>"
    context['table_data'] = table_data
    context['time_form'] = time_form
    context['current_form'] = current_form
    return render(request, 'table.html', context)


def view_analysis(request):
    """This view handles the displaying of the analysed data, being the best timestep aswell as data on
    the utilization rates and queue lengths"""
    context = {}
    best_id = utils.compare(request)
    best_time_step = utils.get_timestep(best_id)
    utils.set_current_time(request, best_time_step)
    df = utils.show_dataframe(best_id)
    result = utils.get_plot_data(request)
    image = str(request.session['data_id'])+".png"
    table_data = df.to_html()
    context["idimage"] = image
    context['table_data'] = table_data
    context['timestep'] = best_time_step.__str__()
    return render(request, 'detail.html', context)

templates/detail.html
<!DOCTYPE HTML>
<!--
	Hyperspace by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
        {% load static %}
		<title>Analysis</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'queuemining/style.css' %}" />
	</head>
	<body class="is-preload">
			<section id="sidebar">
				<div class="inner">
					<nav>
						<ul>

                          	<h3>Your best timestep</h3>

                          	<p>{{ timestep }}</p>

						</ul>
					</nav>
				</div>
			</section>

			<div id="wrapper">


				<!-- Intro -->
					<section id="intro" class="wrapper style1 fullscreen fade-up">

						<div class="inner">
							<h1>Analysis</h1>
							{% autoescape off %}
                                {{ table_data }}
                            {% endautoescape %}


							<img src="{% static 'queuemining/images/'%}{{ idimage}}" class="centerrr"/>
							<p>
								<a href="{% url 'queuemining:get_data' %}"><button>View upload page</button></a>
                            	<a href="{% url 'queuemining:view_table' %}"><button>View table page</button></a>
                          	</p>

						</div>

					</section>
			</div>

			<footer id="footer" class="wrapper style1-alt">
				<div class="inner">
					<ul class="menu">
						<li>Queuemining project for RWTH Aachen</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
					</ul>
				</div>
			</footer>

	</body>
</html>

templates/main.html
<!DOCTYPE HTML>
<!--
	Hyperspace by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
        {% load static %}
		<title>Queuemining</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'queuemining/style.css' %}" />
	</head>
	<body class="is-preload">

			<section id="sidebar">
				<div class="inner">
					<nav>
						<ul>
							<form method="post" enctype="multipart/form-data">
								{% csrf_token %}

								{{ data_form.as_p }}

								<li>
                        			<button type="submit">Submit</button>
								</li>

                    		</form>
						</ul>
					</nav>
				</div>
			</section>

			<div id="wrapper">

				<!-- Intro -->
					<section id="intro" class="wrapper style1 fullscreen fade-up">
						<div class="inner">
							<h1>Queue Mining</h1>
							<p>{{ text }}</p>
							<p><a href="{% url 'queuemining:view_table' %}" onclick="doClick(); return false"><button>View table page</button></a></p>
							<script>
								function doClick(){
									if ("{{text}}"==="Thank you for your upload!"){
										window.location.href = "{% url 'queuemining:view_table' %}"
									}
									else{
										return confirm('Please submit your data first')
									}
								}
							</script>
						</div>
					</section>
			</div>

			<footer id="footer" class="wrapper style1-alt">
				<div class="inner">
					<ul class="menu">
						<li>Queuemining project for RWTH Aachen</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
					</ul>
				</div>
			</footer>

	</body>
</html>

templates/table.html
<!DOCTYPE HTML>
<!--
	Hyperspace by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
        {% load static %}
		<title>Queuemining</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'queuemining/style2.css' %}" />
	</head>

	<body class="is-preload">
			<section id="sidebar">
				<div class="inner">
					<nav>
						<ul>
							<form method="post" enctype="multipart/form-data">
								{% csrf_token %}

                                {{ current_form.as_p }}

                                <p>Choose a timeframe to be visualized</p>

                                <button type="submit" name="current_submit">Submit current</button>


                            </form>

                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}

                                {{ time_form.as_p }}

                                <p>Submit a new time step to compare</p>


                                <button type="submit" name="time_submit">Submit timeframe</button>

                                <p></p>

								<p class="time_text">
									{{ time_text }}
								</p>

                    		</form>
                            <form method="post" enctype="multipart/form-data" onsubmit="return confirm('Do you want to delete?')">
                                {% csrf_token %}
                                <p>
                                    <input type="submit" value="Delete" name="time_delete"/>
                                    <input type="submit" value="Delete All" name="time_delete_all"/>
                                </p>
                                <p>
                                    {{ delete_text }}
                                </p>
                            </form>
                            <p>
                                <a href="{% url 'queuemining:get_data' %}"><button>View upload page</button></a>
                            </p>

						</ul>
					</nav>
				</div>
			</section>

			<div id="wrapper">
					<section id="intro" class="wrapper style1 fullscreen fade-up">
						<div class="inner">
							<h1>Your Table</h1>

                            {% autoescape off %}
                                {{ table_data }}
                            {% endautoescape %}

                            <p>
                                <a href="{% url 'queuemining:view_analysis' %}" onclick="doClick(); return false"><button>Show analysis</button></a>
                            </p>

							<script>
								function doClick(){
									if ("{{ current }}" === "None"){
									    return confirm('Please submit timesteps!')
									}
									else{
										window.location.href = "{% url 'queuemining:view_analysis' %}"
									}
								}
							</script>

						</div>
					</section>
			</div>

			<footer id="footer" class="wrapper style1-alt">
				<div class="inner">
					<ul class="menu">
						<li>Queuemining project for RWTH Aachen</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
					</ul>
				</div>
			</footer>
	</body>
</html>